spring:
  application:
    name: wallet-service
  data:
    mongodb:
      uri: ${MONGO_URI:http://localhost:27017/wallet_db}

aws:
  sns:
    key: ${AWS_ACCESS_KEY_ID:accessKey}
    secret: ${AWS_SECRET_ACCESS_KEY:secretKey}
    region: ${AWS_REGION:us-east-1}
    endpoint: ${SNS_ENDPOINT_OVERRIDE:http://localhost:4566}

logging:
  level:
    root: INFO
    com.example.wallet: DEBUG
  file:
    name: logs/application.log
  loggers:
    audit: logs/audit.log