spring:
  application:
    name: wallet-service
  auth:
    uri: ${AUTH_URI:http://localhost:8000/auth/verify}
  data:
    mongodb:
      uri: ${MONGO_URI:http://localhost:27017/wallet_db}


logging:
  level:
    root: INFO
    com.example.wallet: DEBUG
  file:
    name: logs/application.log
  loggers:
    audit: logs/audit.log